### ISSUE TITLE
can we publish packages for tussle components

### ISSUE THREAD

**Issue by rverma-dev** [Klowner/tussle#14]
Is it possible to publish the packages for tussle components on npm?

**Comment by Klowner** [comment]
If you're referring to the components in this repository, they are all published on npm under the @tussle namespace (eg: https://www.npmjs.com/package/@tussle/core)

If you'd like to contribute a component, PRs are welcome 🙂

**Comment by rverma-dev** [comment]
thanks, but i can see only a subset of packages are published. We are missing packages related to cloudflare middleware etc.

**Comment by Klowner** [comment]
Oh, which are missing?

**Comment by rverma-dev** [comment]
My bad, i found all. For some reason when i search on npm i wasn't able to locate the middleware-cloudflare, i did npm i and it installed.
