### ISSUE TITLE
cloudflare s3 example maybe broken

### ISSUE THREAD

**Issue by phpb-com** [Klowner/tussle#6]
I tried to play with the CF S3 example (using iDrive E2 storage as an S3 endpoint) and always end-up with the objects named 'files' in the root of the bucket. I am not sure what config is required beyond all of the access/secret/endpoint/etc things. For now I gave up since I did not want to spend digging through the layers of code to see where the problem is. If you have a complete working example that I could learn from, that would be great. Thanks.

**Comment by Klowner** [comment]
The `/files` is the endpoint path.
https://github.com/Klowner/tussle/blob/main/examples/cloudflare-worker-s3/src/client.ts#L5

In the `before-create` handler you can alter the location further.

**Comment by Klowner** [comment]
Ah, are you using the parallel uploads feature of the client? That requires that the supports the 
[concatenation](https://tus.io/protocols/resumable-upload.html#concatenation), which tussle currently does not, so you will definitely have poor results.
