### ISSUE TITLE
POST /files 500 Internal Server Error

### ISSUE THREAD

**Issue by MrKevin0308** [Klowner/tussle#9]
Hi
I tried to run `https://github.com/Klowner/tussle/tree/main/examples/cloudflare-worker-r2` example but it didn't work
`const res = await tussle.handleRequest(request, { context });`
tussle.handleRequest() is not working now
Plz help me
```
[mf:err] POST /files: TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable.
    at Object.createInvalidObservableTypeError2 [as createInvalidObservableTypeError] (D:\licensly\node_modules\.pnpm\rxjs@7.8.0\node_modules\rxjs\src\internal\util\throwUnobservableError.ts:7:10)    at Object.innerFrom2 [as innerFrom] (D:\licensly\node_modules\.pnpm\rxjs@7.8.0\node_modules\rxjs\src\internal\observable\innerFrom.ts:41:9)
    at from2 (D:\licensly\node_modules\.pnpm\rxjs@7.8.0\node_modules\rxjs\src\internal\observable\from.ts:103:52)
    at TussleCloudflareWorker2.hook (D:\licensly\node_modules\.pnpm\@tussle+core@0.6.5\node_modules\@tussle\core\src\middleware.ts:16:14)
    at D:\licensly\node_modules\.pnpm\@tussle+core@0.6.5\node_modules\@tussle\core\src\handlers\create.ts:66:41
    at D:\licensly\node_modules\.pnpm\rxjs@7.8.0\node_modules\rxjs\src\internal\operators\switchMap.ts:109:21
    at OperatorSubscriber3._this._next (D:\licensly\node_modules\.pnpm\rxjs@7.8.0\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:70:13)
    at OperatorSubscriber3.Subscriber4.next (D:\licensly\node_modules\.pnpm\rxjs@7.8.0\node_modules\rxjs\src\internal\Subscriber.ts:75:12)
    at D:\licensly\node_modules\.pnpm\rxjs@7.8.0\node_modules\rxjs\src\internal\operators\map.ts:58:20
    at OperatorSubscriber3._this._next (D:\licensly\node_modules\.pnpm\rxjs@7.8.0\node_modules\rxjPOST /files 500 Internal Server Error (142.45ms)```

**Comment by Klowner** [comment]
Can you please provide some information about your environment and the steps you took prior to encountering this error.

**Comment by MrKevin0308** [comment]
-edit the 'wrangler.toml' 
-and run `yarn install` -> `yarn build` -> `yarn dev`

**Comment by Klowner** [comment]
I imagine there are other things that happened, like trying to upload a file via a browser?
Are you using Windows? WSL?
You made no edits to the hooks in the worker.ts ?

**Comment by MrKevin0308** [comment]
I'm using windows and I'm trying to upload a file using chrome browser

**Comment by Klowner** [comment]
Can you copy/paste the entirety of `const getTussleMiddleware = (() => { ...` starting on line 34 of `src/worker.ts` here?

**Comment by MrKevin0308** [comment]
const getTussleMiddleware = (() => {
	let instance: TussleCloudflareWorker<UserParams>;
	return (storage: any) => {
		if (!instance) {
			instance = new TussleCloudflareWorker({
				hooks: {
					"before-create": (_ctx: any, params: any) => {
						let path: string;
						switch (params.uploadConcat?.action) {
							case "partial": // Creating a file to hold a segment of a parallel upload.
								path = params.path + "/segments/" + nanoid();
								break;
							case "final": // Finishing a parallel upload (combines multiple 'partials' from above)
							default:
								path = params.path + "/" + nanoid();
								break;
						}
						return {
							...params,
							path,
						};
					},
					"after-complete": async (ctx: any, params: any) => {
						const { location, offset } = params;
						await cacheCompletedUploadResponse(
							ctx.originalRequest,
							location,
							offset
						);
						return params;
					},
				},
				core: {
					storage,
				},
			});
		}
		return instance;
	};
})();

async function handleRequest(
	request: Request,
	bindings: Bindings,
	context: ExecutionContext
) {
	if (request.method === "HEAD") {
		console.log("looking for cache", request.url);
		const cache = await caches.default.match(request.url);
		console.log({ cache });
		if (cache) {
			return cache;
		}
	}
	const storage = new TussleStorageR2({
		stateService,
		bucket: bindings.TUSSLE_BUCKET,
	});
	const tussle = getTussleMiddleware(storage);
	const res = await tussle.handleRequest(request, { context });
	console.log('1')
	if (res) {
		return res;
	}
	console.log('2')
	const { pathname } = new URL(request.url);
	console.log(3, pathname)
	switch (request.method) {
		case "GET":
			{
				const file = await storage.getFile(pathname);
				if (file) {
					return new Response(file.body);
				}
			}
			break;
		case "HEAD": {
			const info = await firstValueFrom(
				storage.getFileInfo({ location: pathname })
			);
			return new Response(JSON.stringify(info), {
				headers: {
					"Content-Type": "application/json",
				},
			});
		}
	}
	return staticHandler(request);
}

const worker: ExportedHandler<Bindings> = {
	fetch: handleRequest,
};

export default worker;

**Comment by Klowner** [comment]
Looks like you've made a few changes that you did not previously mention.

So, going back to the first line of your original error:
[mf:err] POST /files: TypeError: You provided an invalid object where a stream was expected. You can provide an **Observable, Promise, ReadableStream, Array, AsyncIterable**, or **Iterable.**

The traceback mentions `TussleCloudflareWorker2.hook` so it's likely something hook related.

Your `"before-create"` hook appears to have had the `async` keyword removed from it. With `async`, that function returns a **Promise** (one of the accepted types as mentioned in the error message) but without `async` it returns an **Object**.

Please re-add `async` or change the function to return another Promise-like and try again.

Also remember you can run `git diff` and see what local changes you've made, it may be helpful for finding problems such as this one.

**Comment by MrKevin0308** [comment]
In `before-create` hook, there is no await
so I removed the async

**Comment by Klowner** [comment]
> Please re-add async *or change the function to return another Promise-like* and try again.

**Comment by MrKevin0308** [comment]
Yeah , It works, Thx
And I have other question 
I want to implement this worker in nuxt middleware
Could you give me some suggestion?

**Comment by Klowner** [comment]
I'm not sure I understand what the use case would be as nuxt middleware, is it not a frontend framework?

**Comment by MrKevin0308** [comment]
TNuxt procides server side rendering so I think it's possible to implement that

**Comment by Klowner** [comment]
Sounds like a fun challenge, I would use https://github.com/Klowner/tussle/blob/main/packages/middleware-cloudflareworker/src/middleware.ts as a guide, it's the most recently maintained middleware.
Good luck :+1:

**Comment by MrKevin0308** [comment]
Thx
And Can i use the worker like this ?
`worker.fetch(event.node.req, binding, event.context);`
